# Generated by Django 4.2.7 on 2026-05-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egresado',
            options={'ordering': ['apellido_paterno', 'apellido_materno', 'nombres', 'dni'], 'verbose_name': 'Egresado', 'verbose_name_plural': 'Egresados'},
        ),
        migrations.AddField(
            model_name='egresado',
            name='anio_ingreso',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de ingreso'),
        ),
        migrations.AddField(
            model_name='egresado',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=120, verbose_name='Apellido materno'),
        ),
        migrations.AddField(
            model_name='egresado',
            name='celular',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='egresado',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='egresado',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='egresado',
            name='departamento_nacimiento',
            field=models.CharField(blank=True, max_length=120, verbose_name='Departamento de nacimiento'),
        ),
        migrations.AddField(
            model_name='egresado',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='egresado',
            name='distrito_nacimiento',
            field=models.CharField(blank=True, max_length=120, verbose_name='Distrito de nacimiento'),
        ),
        migrations.AddField(
            model_name='egresado',
            name='escuela',
            field=models.CharField(blank=True, max_length=180, verbose_name='Escuela'),
        ),
        migrations.AddField(
            model_name='egresado',
            name='facultad',
            field=models.CharField(blank=True, max_length=180, verbose_name='Facultad'),
        ),
        migrations.AddField(
            model_name='egresado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='egresado',
            name='nombres',
            field=models.CharField(blank=True, max_length=180, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='egresado',
            name='provincia_nacimiento',
            field=models.CharField(blank=True, max_length=120, verbose_name='Provincia de nacimiento'),
        ),
        migrations.AddField(
            model_name='egresado',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo'),
        ),
    ]
