# Generated by Django 4.2.7 on 2026-05-24 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0003_egresado_anio_egreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encuestas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('titulo', models.CharField(max_length=500, verbose_name='Pregunta')),
                ('tipo', models.CharField(choices=[('seleccion_unica', 'Selección única (lista desplegable)'), ('seleccion_multiple', 'Selección múltiple'), ('texto_largo', 'Texto amplio'), ('texto_corto', 'Texto limitado'), ('entero', 'Número entero'), ('decimal', 'Número decimal')], max_length=30, verbose_name='Tipo de respuesta')),
                ('texto_maximo', models.PositiveSmallIntegerField(blank=True, default=255, null=True, verbose_name='Máximo de caracteres')),
                ('obligatoria', models.BooleanField(default=True, verbose_name='Obligatoria')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='maestro.encuesta', verbose_name='Encuesta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='OpcionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300, verbose_name='Opción')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='maestro.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
                'ordering': ['orden', 'pk'],
            },
        ),
    ]
