# Generated by Django 4.2.7 on 2026-05-24 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0004_encuestas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('seleccion_unica', 'Selección única (lista desplegable)'), ('seleccion_multiple', 'Selección múltiple'), ('matriz_seleccion', 'Matriz de selección (escala por fila)'), ('texto_largo', 'Texto amplio'), ('texto_corto', 'Texto limitado'), ('entero', 'Número entero'), ('decimal', 'Número decimal')], max_length=30, verbose_name='Tipo de respuesta'),
        ),
        migrations.CreateModel(
            name='FilaMatrizPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500, verbose_name='Ítem')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas_matriz', to='maestro.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Fila de matriz',
                'verbose_name_plural': 'Filas de matriz',
                'ordering': ['orden', 'pk'],
            },
        ),
    ]
