# Generated by Django 4.2.7 on 2026-05-24 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0005_matriz_seleccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada_en', models.DateTimeField(auto_now_add=True, verbose_name='Completada en')),
                ('egresado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_encuestas', to='maestro.egresado', verbose_name='Egresado')),
            ],
            options={
                'verbose_name': 'Respuesta de encuesta',
                'verbose_name_plural': 'Respuestas de encuestas',
            },
        ),
        migrations.CreateModel(
            name='RespuestaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, verbose_name='Texto')),
                ('valor_entero', models.IntegerField(blank=True, null=True, verbose_name='Entero')),
                ('valor_decimal', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Decimal')),
                ('opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_seleccion', to='maestro.opcionpregunta', verbose_name='Opción seleccionada')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='maestro.pregunta', verbose_name='Pregunta')),
                ('respuesta_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_preguntas', to='maestro.respuestaencuesta', verbose_name='Respuesta de encuesta')),
            ],
            options={
                'verbose_name': 'Respuesta a pregunta',
                'verbose_name_plural': 'Respuestas a preguntas',
            },
        ),
        migrations.AddField(
            model_name='encuesta',
            name='alcance',
            field=models.CharField(choices=[('todos', 'Todos los egresados'), ('escuela', 'Solo una escuela')], default='todos', max_length=20, verbose_name='Alcance'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='escuela',
            field=models.CharField(blank=True, max_length=180, verbose_name='Escuela'),
        ),
        migrations.CreateModel(
            name='RespuestaPreguntaOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_multiples', to='maestro.opcionpregunta')),
                ('respuesta_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_seleccionadas', to='maestro.respuestapregunta')),
            ],
            options={
                'verbose_name': 'Opción seleccionada (múltiple)',
                'verbose_name_plural': 'Opciones seleccionadas (múltiple)',
            },
        ),
        migrations.CreateModel(
            name='RespuestaMatriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='maestro.filamatrizpregunta', verbose_name='Fila')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_matriz_celda', to='maestro.opcionpregunta', verbose_name='Columna seleccionada')),
                ('respuesta_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_matriz', to='maestro.respuestaencuesta', verbose_name='Respuesta de encuesta')),
            ],
            options={
                'verbose_name': 'Respuesta de matriz',
                'verbose_name_plural': 'Respuestas de matriz',
            },
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='maestro.encuesta', verbose_name='Encuesta'),
        ),
        migrations.AddConstraint(
            model_name='respuestapreguntaopcion',
            constraint=models.UniqueConstraint(fields=('respuesta_pregunta', 'opcion'), name='uniq_respuesta_pregunta_opcion'),
        ),
        migrations.AddConstraint(
            model_name='respuestapregunta',
            constraint=models.UniqueConstraint(fields=('respuesta_encuesta', 'pregunta'), name='uniq_respuesta_pregunta'),
        ),
        migrations.AddConstraint(
            model_name='respuestamatriz',
            constraint=models.UniqueConstraint(fields=('respuesta_encuesta', 'fila'), name='uniq_respuesta_matriz_fila'),
        ),
        migrations.AddConstraint(
            model_name='respuestaencuesta',
            constraint=models.UniqueConstraint(fields=('encuesta', 'egresado'), name='uniq_respuesta_encuesta_egresado'),
        ),
    ]
